airport_timezones:
  CAK: "America/New_York"
  SFO: "America/Los_Angeles"
  LAX: "America/Los_Angeles"
  BWI: "America/New_York"
  BOS: "America/New_York"
  BUR: "America/Los_Angeles"
  CLT: "America/New_York"
  MDW: "America/Chicago"
  ORD: "America/Chicago"
  CLE: "America/New_York"
  DFW: "America/Chicago"
  DAL: "America/Chicago"
  DEN: "America/Denver"
  DTW: "America/Detroit"
  FLL: "America/New_York"
  HOU: "America/Chicago"
  IAH: "America/Chicago"
  HNL: "Pacific/Honolulu"
  ISP: "America/New_York"
  OGG: "Pacific/Honolulu"
  KOA: "Pacific/Honolulu"
  MCI: "America/Chicago"
  LAS: "America/Los_Angeles"
  LIH: "Pacific/Honolulu"
  LHR: "Europe/London"
  LGW: "Europe/London"
  LGB: "America/Los_Angeles"
  MHT: "America/New_York"
  MEM: "America/Chicago"
  MIA: "America/New_York"
  MSP: "America/Chicago"
  BNA: "America/Chicago"
  MSY: "America/Chicago"
  JFK: "America/New_York"
  LGA: "America/New_York"
  EWR: "America/New_York"
  ORF: "America/New_York"
  OAK: "America/Los_Angeles"
  ONT: "America/Los_Angeles"
  SNA: "America/Los_Angeles"
  PBI: "America/New_York"
  ORY: "Europe/Paris"
  PHL: "America/New_York"
  PHX: "America/Phoenix"
  PDX: "America/Los_Angeles"
  PVD: "America/New_York"
  SMF: "America/Los_Angeles"
  STL: "America/Chicago"
  PIE: "America/New_York"
  SLC: "America/Denver"
  SAN: "America/Los_Angeles"
  SJC: "America/Los_Angeles"
  SRQ: "America/New_York"
  SEA: "America/Los_Angeles"
  TPA: "America/New_York"
  YYZ: "America/Toronto"
  TUS: "America/Phoenix"
  IAD: "America/New_York"
  DCA: "America/New_York"
  HPN: "America/New_York"
  AUS: "America/Chicago"
  EDI: "Europe/London"
  BDL: "America/New_York"
  MKE: "America/Chicago"
  ORH: "America/New_York"
  MCO: "America/New_York"
  PSM: "America/New_York"
  HDN: "America/Denver"
  ILG: "America/New_York"
  RDU: "America/New_York"
  ABQ: "America/Denver"
  RSW: "America/New_York"
  GUC: "America/Denver"
  ATL: "America/New_York"
  RNO: "America/Los_Angeles"
  AZA: "America/Phoenix"
  PIT: "America/New_York"
  CDG: "America/Chicago"
  SAT: "America/Edmonton"
  IND: "Eastern Time (US & Canada)"
  SFB: "America/New_York"
  RAP: "America/Denver"
  JAX: "Asia/Tehran"
  SDF: "America/Edmonton"
  CVG: "Africa/Lagos"
  SBA: "America/Sao_Paulo"
  PUJ: "America/Santo_Domingo"
  SDQ: "America/Puerto_Rico"
  POP: "America/Santo_Domingo"
  MEX: "America/Mexico_City"
  SJU: "America/New_York"
  OKC: "America/Havana"
  ANC: "America/Anchorage"
  CUN: "America/Sao_Paulo"
  RIC: "America/New_York"
  FNT: "America/Detroit"
  ABE: "America/New_York"
  CMH: "America/New_York"
